### ISSUE TITLE
undefined method `accept' for nil:NilClass Extracted source (around line #11):

### ISSUE THREAD

**Issue by masterkain** [rapid7/jsobfu#19]
![Screenshot 2020-05-02 at 20 38 03](https://user-images.githubusercontent.com/12844/80872844-db54ef80-8cb4-11ea-9051-0e64d813a59d.png)

**Comment by bcoles** [comment]
This occurs when the provided text is not valid JavaScript. For example:

```
# cat ./spec/integration/void.js | bundle exec ./bin/jsobfu  
function K(){return void(((011*6+1)+'AvuNo'.length-('O'.length*104297+18826)+(function () { var l="LO",q="EL",y="H"; return y+q+l })()[(String.fromCharCode(0x6c,0x65,0x6e,0147,116,0150))]));}this[(String.fromCharCode(0x74,0x65,0x73,116))]=function(){if(K()!==window[String.fromCharCode(117,0156,0144,0x65,102,0151,0x6e,0145,0144)])throw (function () { var g='ECTED',a='UNEXP'; return a+g })();return String.fromCharCode(0166,0157,105,0144,32,0151,115,0x20,0167,0157,0162,107,0151,0156,103,46);};
```

```
# echo asdf | bundle exec ./bin/jsobfu  
window[(function () { var b="f",e="sd",B="a"; return B+e+b })()];
```

```
# echo "<html>asdf" | bundle exec ./bin/jsobfu  
bundler: failed to load command: ./bin/jsobfu (./bin/jsobfu)
/var/lib/gems/3.3.0/gems/rkelly-remix-0.0.7/lib/rkelly/visitors/visitor.rb:38:in `accept': undefined method `accept' for nil (NoMethodError)

        target.accept(self)
              ^^^^^^^
        from /root/Desktop/jsobfu/lib/jsobfu.rb:76:in `block in obfuscate'
        from <internal:numeric>:237:in `times'
        from /root/Desktop/jsobfu/lib/jsobfu.rb:74:in `obfuscate'
        from /root/Desktop/jsobfu/bin/jsobfu:24:in `<top (required)>'
        from /var/lib/gems/3.3.0/gems/bundler-2.6.8/lib/bundler/cli/exec.rb:59:in `load'
        from /var/lib/gems/3.3.0/gems/bundler-2.6.8/lib/bundler/cli/exec.rb:59:in `kernel_load'
        from /var/lib/gems/3.3.0/gems/bundler-2.6.8/lib/bundler/cli/exec.rb:23:in `run'
        from /var/lib/gems/3.3.0/gems/bundler-2.6.8/lib/bundler/cli.rb:452:in `exec'
        from /var/lib/gems/3.3.0/gems/bundler-2.6.8/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /var/lib/gems/3.3.0/gems/bundler-2.6.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/lib/gems/3.3.0/gems/bundler-2.6.8/lib/bundler/vendor/thor/lib/thor.rb:538:in `dispatch'
        from /var/lib/gems/3.3.0/gems/bundler-2.6.8/lib/bundler/cli.rb:35:in `dispatch'
        from /var/lib/gems/3.3.0/gems/bundler-2.6.8/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /var/lib/gems/3.3.0/gems/bundler-2.6.8/lib/bundler/cli.rb:29:in `start'
        from /var/lib/gems/3.3.0/gems/bundler-2.6.8/exe/bundle:28:in `block in <top (required)>'
        from /var/lib/gems/3.3.0/gems/bundler-2.6.8/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /var/lib/gems/3.3.0/gems/bundler-2.6.8/exe/bundle:20:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
```
